version: '3.4'

services:
   xershade.ca.website:
    image: xershade/xershade.website
    build:
      context: .
      dockerfile: source/Reoria.Server/Dockerfile
    volumes:
        - "application_data:/app"
        - "common_data:/app/common"
    environment:
      ASPNETCORE_ENVIRONMENT: "Release"
    container_name: xershade.website

volumes:
  application_data:
  common_data:

networks:
  default:
    external:
      name: system.nginx.proxy
