version: '3.4'

services:
   xershade.ca.website:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
        - "app_data:/app/App_Data"
     expose:
        - 80
     restart: unless-stopped
     environment:
        VIRTUAL_HOST: website.xershade.ca
        LETSENCRYPT_HOST: website.xershade.ca
        LETSENCRYPT_EMAIL: xershade.ca@gmail.com
        ASPNETCORE_HTTP_PORTS: 80
     container_name: xershade.ca.website

volumes:
  app_data:

networks:
  default:
    external:
      name: system.nginx.proxy
